export default {
    1: {
        name: "Cizib3ken",
        width: 75,
        height: 75,
        life: 1,
        healthBArColor: 0xff8712,
        speed: 2,
    },
    2: {
        name: "dekodans",
        width: 75,
        height: 75,
        life: 2,
        healthBArColor: 0x128012,
        speed: 2,
    },
    3: {
        name: "ganjamurder",
        width: 75,
        height: 75,
        life: 3,
        healthBArColor: 0xf9991c,
        speed: 2,
    },
    4: {
        name: "tvoi_bratan",
        width: 75,
        height: 120,
        life: 4,
        healthBArColor: 0xffff91,
        speed: 2,
    },
    5: {
        name: "TrapDiller",
        width: 75,
        height: 120,
        life: 1,
        healthBArColor: 0x129f1c,
        speed: 2,
    },
    6: {
        name: "OZMEN",
        width: 75,
        height: 87,
        life: 1,
        healthBArColor: 0x129f1c,
        speed: 2,
    },
    7: {
        name: "pozytron",
        width: 75,
        height: 75,
        life: 1,
        healthBArColor: 0x129f1c,
        speed: 2,
    },
    8: {
        name: "jEKS0N",
        width: 75,
        height: 93,
        life: 1,
        healthBArColor: 0x129f1c,
        speed: 2,
    },
    9: {
        name: "Liunk",
        width: 75,
        height: 104,
        life: 1,
        healthBArColor: 0x129f1c,
        speed: 2,
    },
    10: {
        name: "Chemius",
        width: 75,
        height: 86,
        life: 1,
        healthBArColor: 0x129f1c,
        speed: 2,
    },
    11: {
        name: "99THC",
        width: 75,
        height: 101,
        life: 1,
        healthBArColor: 0x129f1c,
        speed: 2,
    },
    12: {
        name: "st228",
        width: 75,
        height: 104,
        life: 1,
        healthBArColor: 0x129f1c,
        speed: 2,
    },
    13: {
        name: "solevik_1",
        width: 75,
        height: 96,
        life: 1,
        healthBArColor: 0x129f1c,
        speed: 2,
    },
    14: {
        name: "solevik_2",
        width: 75,
        height: 104,
        life: 1,
        healthBArColor: 0x129f1c,
        speed: 2,
    },
    15: {
        name: "solevik_3",
        width: 75,
        height: 104,
        life: 1,
        healthBArColor: 0x129f1c,
        speed: 2,
    },
    16: {
        name: "solevik_4",
        width: 75,
        height: 104,
        life: 1,
        healthBArColor: 0x129f1c,
        speed: 2,
    },
    17: {
        name: "solevik_5",
        width: 75,
        height: 83,
        life: 1,
        healthBArColor: 0x129f1c,
        speed: 2,
    },
    18: {
        name: "solevik_6",
        width: 75,
        height: 86,
        life: 1,
        healthBArColor: 0x129f1c,
        speed: 2,
    },
    19: {
        name: "solevik_7",
        width: 75,
        height: 112,
        life: 1,
        healthBArColor: 0x129f1c,
        speed: 2,
    },
    20: {
        name: "shvir_1",
        width: 75,
        height: 86,
        life: 1,
        healthBArColor: 0x129f1c,
        speed: 2,
    },
    21: {
        name: "shvir_2",
        width: 75,
        height: 83,
        life: 1,
        healthBArColor: 0x129f1c,
        speed: 2,
    },
    22: {
        name: "shvir_3",
        width: 75,
        height: 112,
        life: 1,
        healthBArColor: 0x129f1c,
        speed: 2,
    },
    23: {
        name: "shvir_4",
        width: 75,
        height: 101,
        life: 1,
        healthBArColor: 0x129f1c,
        speed: 2,
    },
    24: {
        name: "shvir_5",
        width: 75,
        height: 86,
        life: 1,
        healthBArColor: 0x129f1c,
        speed: 2,
    },
    25: {
        name: "shvir_6",
        width: 75,
        height: 86,
        life: 1,
        healthBArColor: 0x129f1c,
        speed: 2,
    },
    26: {
        name: "shvir_7",
        width: 75,
        height: 104,
        life: 1,
        healthBArColor: 0x129f1c,
        speed: 2,
    },
    27: {
        name: "boss_1",
        width: 150,
        height: 217,
        life: 20,
        healthBArColor: 0xff2211,
        speed: 4,
    },
    28: {
        name: "boss_2",
        width: 150,
        height: 172,
        life: 20,
        healthBArColor: 0xff2211,
        speed: 4,
    },
    29: {
        name: "boss_3",
        width: 150,
        height: 221,
        life: 20,
        healthBArColor: 0xff2211,
        speed: 4,
    },
    30: {
        name: "boss_4",
        width: 150,
        height: 208,
        life: 20,
        healthBArColor: 0xff2211,
        speed: 4,
    },
};
