const STYLES = {
    score: {
        align: "center",
        dropShadow: true,
        dropShadowAngle: 0.4,
        dropShadowColor: "#0d1144",
        dropShadowDistance: 2,
        fill: "#857833",
        fillGradientStops: [1],
        fontFamily: "Comic Sans MS",
        fontSize: 40,
        fontWeight: 900,
        letterSpacing: 2,
        lineJoin: "round",
        miterLimit: 5,
        padding: 4,
        stroke: "#f64949",
        strokeThickness: 2,
        whiteSpace: "normal",
    },
    lives: {
        align: "center",
        dropShadow: true,
        dropShadowAngle: 0.4,
        dropShadowColor: "#0d1144",
        dropShadowDistance: 1,
        fill: "#857833",
        fillGradientStops: [1],
        fontFamily: "Comic Sans MS",
        fontSize: 20,
        fontWeight: 900,
        letterSpacing: 2,
        lineJoin: "round",
        miterLimit: 5,
        padding: 4,
        stroke: "#f64949",
        strokeThickness: 2,
        whiteSpace: "normal",
    },
    IntroPlayerName: {
        align: "center",
        dropShadow: true,
        dropShadowAngle: 0.4,
        dropShadowColor: "#0d1144",
        dropShadowDistance: 2,
        fill: "#857833",
        fillGradientStops: [1],
        fontFamily: "Comic Sans MS",
        fontSize: 30,
        fontWeight: 900,
        letterSpacing: 2,
        lineJoin: "round",
        miterLimit: 5,
        padding: 4,
        stroke: "#f64949",
        strokeThickness: 2,
        whiteSpace: "normal",
    },
    miniBoss: {
        align: "center",
        dropShadow: true,
        dropShadowAlpha: 0.6,
        dropShadowAngle: 1,
        dropShadowBlur: 3,
        dropShadowColor: "#121612",
        dropShadowDistance: 2,
        fill: "#cc5353",
        fillGradientStops: [0.8],
        fontFamily: "Comic Sans MS",
        fontSize: 24,
        fontWeight: 900,
        letterSpacing: 1,
        lineHeight: 1,
        lineJoin: "round",
        miterLimit: 11,
        stroke: "#23291e",
        strokeThickness: 2,
        whiteSpace: "normal",
    },
    logo: {
        align: "center",
        dropShadow: true,
        dropShadowAlpha: 0.6,
        dropShadowAngle: 1,
        dropShadowBlur: 3,
        dropShadowColor: "#121612",
        dropShadowDistance: 2,
        fill: "#cc5353",
        fillGradientStops: [0.8],
        fontFamily: "Comic Sans MS",
        fontSize: 54,
        fontWeight: 900,
        letterSpacing: 16,
        lineHeight: 1,
        lineJoin: "round",
        miterLimit: 11,
        stroke: "#23291e",
        strokeThickness: 2,
        whiteSpace: "normal",
    },
};

export default STYLES;
